name: Run Gradle test

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: eskatos/gradle-command-action@v2.0.1
      name: gradle test
      with:
        arguments: test
