name: Run Gradle test

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: gradle/gradle-build-action@v2.1.0
      name: gradle test
      with:
        arguments: test
